const searchStocks = [
  { ticker: 'AAL', name: 'American Airlines Group Inc' },
  { ticker: 'AAPL', name: 'Apple Inc' },
  { ticker: 'ACB', name: 'Aurora Cannabis Inc' },
  { ticker: 'AMC', name: 'AMC Entertainment Holdings Inc - Class A' },
  { ticker: 'AMD', name: 'Advanced Micro Devices Inc.' },
  { ticker: 'AMZN', name: 'Amazon.com Inc.' },
  { ticker: 'APHA', name: 'Aphria Inc' },
  { ticker: 'ARKK', name: 'ARK Investment Management LLC - ARK Innovation ETF' },
  { ticker: 'BABA', name: 'Alibaba Group Holding Ltd - ADR' },
  { ticker: 'BAC', name: 'Bank Of America Corp.' },
  { ticker: 'BB', name: 'BlackBerry Ltd' },
  { ticker: 'BNGO', name: 'Bionano Genomics Inc' },
  { ticker: 'CCL', name: 'Carnival Corp. (Paired Stock)' },
  { ticker: 'CGC', name: 'Canopy Growth Corporation' },
  { ticker: 'CRM', name: 'Salesforce.Com Inc' },
  { ticker: 'DAL', name: 'Delta Air Lines, Inc.' },
  { ticker: 'DKNG', name: 'DraftKings Inc - Class A' },
  { ticker: 'DIS', name: 'Walt Disney Co (The)' },
  { ticker: 'EBAY', name: 'EBay Inc.' },
  { ticker: 'F', name: 'Ford Motor Co.' },
  { ticker: 'FB', name: 'Facebook Inc - Class A' },
  { ticker: 'FCEL', name: 'Fuelcell Energy Inc' },
  { ticker: 'GE', name: 'General Electric Co.' },
  { ticker: 'GM', name: 'General Motors Company' },
  { ticker: 'GME', name: 'Gamestop Corporation - Class A' },
  { ticker: 'GNUS', name: 'Genius Brands International Inc' },
  { ticker: 'GOOGL', name: 'Alphabet Inc - Class A' },
  { ticker: 'GPRO', name: 'GoPro Inc. - Class A' },
  { ticker: 'HAS', name: 'Hasbro, Inc.' },
  { ticker: 'IDEX', name: 'Ideanomics Inc' },
  { ticker: 'INO', name: 'Inovio Pharmaceuticals Inc' },
  { ticker: 'JNJ', name: 'Johnson & Johnson' },
  { ticker: 'KO', name: 'Coca-Cola Co' },
  { ticker: 'LI', name: 'Li Auto Inc - ADR' },
  { ticker: 'MRNA', name: 'Moderna Inc' },
  { ticker: 'MSFT', name: 'Microsoft Corporation' },
  { ticker: 'NFLX', name: 'NetFlix Inc' },
  { ticker: 'NIO', name: 'NIO Inc - ADR' },
  { ticker: 'NKE', name: 'Nike, Inc. - Class B' },
  { ticker: 'NOK', name: 'Nokia Corp - ADR' },
  { ticker: 'NNDM', name: 'Nano Dimension Ltd - ADR' },
  { ticker: 'NVDA', name: 'NVIDIA Corp' },
  { ticker: 'ORCL', name: 'Oracle Corp.' },
  { ticker: 'PYPL', name: 'PayPal Holdings Inc' },
  { ticker: 'PTON', name: 'Peloton Interactive Inc - Class A' },
  { ticker: 'PLTR', name: 'Palantir Technologies Inc - Class A' },
  { ticker: 'PFE', name: 'Pfizer Inc.' },
  { ticker: 'PLUG', name: 'Plug Power Inc' },
  { ticker: 'QCOM', name: 'Qualcomm, Inc.' },
  { ticker: 'RIOT', name: 'Riot Blockchain Inc' },
  { ticker: 'SBUX', name: 'Starbucks Corp.' },
  { ticker: 'SNAP', name: 'Snap Inc - Class A' },
  { ticker: 'SNDL', name: 'Sundial Growers Inc' },
  { ticker: 'SNE', name: 'Sony Corporation. - ADR' },
  { ticker: 'SPCE', name: 'Virgin Galactic Holdings Inc - Class A' },
  { ticker: 'SPY', name: 'SSgA Active Trust - SSGA SPDR S&P 500' },
  { ticker: 'SQ', name: 'Square Inc - Class A' },
  { ticker: 'TME', name: 'Tencent Music Entertainment Group - ADR' },
  { ticker: 'TSLA', name: 'Tesla Inc' },
  { ticker: 'TWTR', name: 'Twitter Inc' },
  { ticker: 'UBER', name: 'Uber Technologies Inc' },
  { ticker: 'VOO', name: 'Vanguard Group, Inc. - Vanguard S&P 500 ETF' },
  { ticker: 'WKHS', name: 'Workhorse Group Inc' },
  { ticker: 'WMT', name: 'Walmart Inc' },
  { ticker: 'XRX', name: 'Xerox Holdings Corp' },
  { ticker: 'YELP', name: 'Yelp Inc' },
  { ticker: 'ZM', name: 'Zoom Video Communications Inc - Class A' },
  { ticker: 'ZNGA', name: 'Zynga Inc - Class A' },
  { ticker: 'ZOM', name: 'Zomedica Corp' },
];

export default searchStocks;
